# Generated by Django 3.2 on 2022-06-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_profile_major'),
        ('master', '0003_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Major',
        ),
    ]
