# Generated by Django 3.2 on 2022-06-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_class_of'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='major',
        ),
    ]
